name: bc_ur
description: Dart port of https://github.com/ngraveio/bc-ur
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cbor: ^5.0.1
  convert: ^3.0.1
  crclib: ^3.0.0
  crypto: ^3.0.2
  decimal: ^2.2.0
  typed_data: ^1.3.1
  xrandom: ^0.7.2
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
